import { readdir, mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';

const contentDirectory = join(process.cwd(), 'content', 'posts');
const outputDirectory = join(process.cwd(), 'src', 'app', 'generated');
const requiredFields = ['title', 'date', 'description', 'category'];
const files = (await readdir(contentDirectory)).filter((file) => file.endsWith('.md'));

const posts = await Promise.all(files.map(async (file) => {
  const source = await readFile(join(contentDirectory, file), 'utf8');
  const { data, content } = matter(source);
  const missingFields = requiredFields.filter((field) => !data[field]);
  if (missingFields.length) throw new Error(`${file} is missing: ${missingFields.join(', ')}`);

  return {
    title: String(data.title),
    date: new Date(data.date).toISOString(),
    description: String(data.description),
    featuredImage: data.featuredImage ? String(data.featuredImage) : 'images/post-placeholder.svg',
    category: String(data.category),
    slug: basename(file, '.md'),
    bodyHtml: await marked.parse(content),
  };
}));

posts.sort((a, b) => b.date.localeCompare(a.date));
await mkdir(outputDirectory, { recursive: true });
await writeFile(
  join(outputDirectory, 'posts.ts'),
  `// Generated by npm run content:build. Edit content/posts instead.\nimport { BlogPostData } from '../blog/blog-post.model';\n\nexport const posts: readonly BlogPostData[] = ${JSON.stringify(posts, null, 2)};\n`,
);
console.log(`Prepared ${posts.length} blog posts.`);
